CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL
);


INSERT INTO USUARIO (NOME, ENDERECO) VALUES ('João Silva', 'Rua A, 123');
INSERT INTO USUARIO (NOME, ENDERECO) VALUES ('Maria Souza', 'Avenida B, 456');
